#https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token
#https://github.com/kubernetes/kubernetes/issues/66020#issuecomment-590413238
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sa-token
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}
type: kubernetes.io/service-account-token
