egressIps: []
egressPoolName: ""
saMountPath: "/var/run/secrets/kubernetes.io/operator-serviceaccount"
doAccessToken: ""

image:
    name: "quay.io/vsychov/digitalocean-floating-ip-operator"
    tag: "v0.1.9"
